--================================
--Exploratory Data Analysis (EDA)
--================================

--Explore all objects in the DB
select * from INFORMATION_SCHEMA.tables

--Explore all columns in our DB
select * from INFORMATION_SCHEMA.columns
where TABLE_NAME= 'fact_sales'

--Explore for all counteries that the customer came from
select distinct country 
from gold.dim_customer

--Explore number of male \ female
select distinct(select count(*) from gold.dim_customer where gender='Female') as num_of_Female,
	   (select count(*) from gold.dim_customer where gender='Male') as num_of_male
from gold.dim_customer

--Explore the marital_status
select distinct marital_status from gold.dim_customer
select distinct 
		(select count(*) from gold.dim_customer where marital_status='Single') as num_of_singles,
	    (select count(*) from gold.dim_customer where marital_status='Married') as num_of_marrieds
from gold.dim_customer

--Explore how many men are married and how many women are married
select  
	gender , 
	count(case when marital_status = 'Single' then 1 end) as single,
	count(case when marital_status = 'Married' then 1 end) as married
from gold.dim_customer
where marital_status in ('Single', 'Married','n\a')
group by gender

--Explore the num of category and subcategroy 
select distinct count(category_id) from gold.dim_products

--Explore dates
select 
	min(order_date) as first_order_date,
	max(order_date) as last_order_date,
	datediff(MONTH,min(order_date), max(order_date)) as range_of_sales
from gold.fact_sales

--the oldest customer & youngest
select 
	min(birth_date) as youngest_cust,
	max(birth_date) as oldest_cust,
	datediff(year,min(birth_date),max(birth_date)) as diff_age
from gold.dim_customer

-------------##
--key matric 
-------------##

--the total sales
select sum(sales_amount) as [total sales]
from gold.fact_sales

--find how many items are solds 
select sum(quantity) as num_items from gold.Fact_Sales

--find the avg selling price
select avg(price) as avg_price from gold.Fact_Sales
select * from gold.Fact_Sales

 --find the total number of orders 
 select count(distinct order_number) as num_orders from gold.Fact_Sales

 --find the total number of products 
 select count( distinct product_key) as num_product from gold.Fact_Sales

 --find the total number of customers 
 select count( customer_key) as num_of_customer from gold.dim_customer

 --find the total number of customers that has placed an order
 select count(distinct customer_number) as num_customer from gold.Fact_Sales

 --this report show the all key  matrix of business:

select 'Total sales' as [measure name], sum(sales_amount) as [measure value] from gold.fact_sales 
union all 
select 'Total quantity' ,sum(quantity)  from gold.Fact_Sales
union all 
select 'Average price', avg(price) from gold.Fact_Sales
union all 
select 'Number of orders' , count(distinct order_number) from gold.Fact_Sales
union all 
select 'Number of products', count( distinct product_key) from gold.Fact_Sales
union all 
select 'Number of cutomers' , count( customer_key) from gold.dim_customer
union all 
select 'Num_of_cust_placed' , count(distinct customer_number) from gold.Fact_Sales

 ------------#
 --Magnitude 
 ------------#

--find the number of customer by country 
select country , count(customer_key) as num_of_customer 
from gold.dim_customer
group by country 
order by country DESC

--find the total number of cutomer by gender 
select gender , count(customer_key) as num_of_customer
from gold.dim_customer
group by gender 
order by num_of_customer DESC

--find the total product by category 
select category , count(product_id) as total_products
from gold.dim_products 
group by category
order by total_products DESC

--find the average costs in each category 
select category , Round(avg(product_cost),2) as avg_cost
from gold.dim_products
group by category
order by avg_cost DESC

--find the total revenue generated from each category ?
select dp.category , sum(f.price) as total_revenue
from gold.Fact_Sales f
left join  gold.dim_products dp
	on f.product_id= dp.product_id
group by dp.category 
order by total_revenue DESC

--what is the total revenue generated by each customer?
select f.customer_id,cst.firstname,sum(f.sales_amount) as total_sales
from gold.dim_customer cst 
left join gold.Fact_Sales f 
	on cst.customer_id=f.customer_id
group by f.customer_id,cst.firstname
order by total_sales DESC

--what is the distribution of sold items across countries?
select cst.country, count(quantity) as total_items 
from gold.dim_customer cst
left join gold.Fact_Sales f
	on cst.customer_id=f.customer_id
group by cst.country 
order by total_items DESC

-----------
--Ranking #
-----------
--which products generated the highest revenue?
select top 5 p.product_name,sum(f.sales_amount) as total_revenue
from gold.dim_products p
left join gold.Fact_Sales f
	on f.product_id = p.product_id
group by f.product_id,p.product_name
order by total_revenue DESC


--using window functions
select * 
from(
	select  p.product_name,sum(f.sales_amount) as total_revenue,
	Rank()over(order by sum(f.sales_amount) DESC) as rnk
	from gold.dim_products p
	left join gold.Fact_Sales f
		on f.product_id = p.product_id
	group by f.product_id,p.product_name
) as sub
where rnk <=5
order by rnk 

---which customers generated the highest revenue?
select * 
from(
	select  cst.firstname,sum(f.sales_amount) as total_revenue,
	Rank()over(order by sum(f.sales_amount) DESC) as rnk
	from gold.dim_customer cst
	left join gold.Fact_Sales f
		on f.customer_id = cst.customer_id
	group by f.customer_id,cst.firstname
) as sub
where rnk <=5
order by rnk 


